### ISSUE TITLE
How do I use the files?

### ISSUE THREAD

**Issue by meskarune** [cj-sv/equilux-firefox#1]
Could you put some information in the readme about how these files are used to theme firefox? Thanks!

**Comment by cj-sv** [comment]
Oh, sure thing.

1. In your Firefox address bar, go to about:profiles, open your profile's directory in 'Open Directory".

![image](https://user-images.githubusercontent.com/11567756/36652954-072c3bae-1aed-11e8-807b-9978e0fe553b.png)


2. In your profile's directory, create a 'chrome' folder if it doesn't exist. Extract the userChrome.css and userContent.css into the folder. 

![image](https://user-images.githubusercontent.com/11567756/36653026-7f63a1fc-1aed-11e8-80cf-11541bb31466.png)

If you already have an existing userChrome.css and userContent.css, you may copy the code snippets and append it to the corresponding file.

**Comment by meskarune** [comment]
Thanks! This is a life saver because the white flash from loading and new tabs actually triggers migraines for me. There are probably other people with light sensitive epilepsy who could also really benefit from your work.
