### ISSUE TITLE
No dark new tab content on Firefox Nightly v61

### ISSUE THREAD

**Issue by aquatix** [cj-sv/equilux-firefox#2]
Since a week or so, this theme stopped working, as I guess Mozilla changed the new tab contents a bit again.

I stumbled upon this story in their own tracker: https://github.com/mozilla/activity-stream/pull/4044 in which they added support for dark themes.

Maybe this can be used to make it more equilux-y?

Anyway, thanks for creating this theme! Let me know how/if I can help fixing it in the latest Firefox.

**Comment by cj-sv** [comment]
Yep, can confirm since the recent updates. So far setting new tab as about:blank still works. I haven't found a work around for about:home yet. Looks like the background color does load but gets replaced by how they themed it.

**Comment by aquatix** [comment]
Interesting, even the div with id="root" which I would expect to supply the background colour, does not want to be styled (from the element inspector). I'll keep on digging, but I wonder what magic they did here :)

**Comment by cj-sv** [comment]
Found a fix. :D Will update soon.
